default_language_version:
  python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: ["--line-length=79"]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: ["--ignore=E501,E203"]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/python-poetry/poetry
    rev: 1.2.0b3
    hooks:
    -   id: poetry-check
    -   id: poetry-lock

-   repo: local
    hooks:
    -   id: unittests
        name: run unit tests
        entry: poetry run test
        language: system
        pass_filenames: false
